import { DeviseTables } from './types';
import { convertDateToEpoch, convertUnixToIST } from 'utils/timeFunctions';

let nowDate = new Date();
const epochNow = convertDateToEpoch(nowDate);
const commisionedTime = convertUnixToIST(1720533630);

const time = convertUnixToIST(epochNow);
const data: DeviseTables[] = [
    {
        device_id: 'Outdoor unit 1',
        sensor_address: 'CEM24001',

        customer: 'Panasonic',
        seat_no: 'Bangalore',
        building: 'Brigade Signature Towers',
        floor: '14',
        health_status: 'ON',
        last_refreshed_on: time,
        last_diagnosed_on: commisionedTime,
        // '2024-07-09 19.30',
        battery_level: '70',
    },

    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'OFF',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
    // {
    //     sensor_address: 'C2B/S2A',
    //     seat_no: '1',
    //     building: '33',
    //     floor: '2',
    //     health_status: 'ON',
    //     last_refreshed_on: '14th Jan 7:30pm',
    //     last_diagnosed_on: '14th Jan 7:30pm',
    //     battery_level: '70',
    // },
];

export { data };
