import { SiteComparision } from './types';

const data: SiteComparision[] = [
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'OFF',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
    {
        sensor_address: 'C2B/S2A',
        seat_no: '1',
        building: '33',
        floor: '2',
        health_status: 'ON',
        last_refreshed_on: '14th Jan 7:30pm',
        last_diagnosed_on: '14th Jan 7:30pm',
        battery_level: '70',
    },
];

export { data };
