import { CustomerTables } from './types';

const data: CustomerTables[] = [
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },

    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
    {
        customerName: 'Customer 1',
        numberOfDevices: 6,
        numberOfUsers: 16,
        timeCreated: '2024-05-18',
        numberOfAlerts: 18,
        status: 'Offline',
        action: 'View',
    },
];

export { data };
